# Generated by Django 4.0.4 on 2022-05-08 12:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drugstore', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.ManyToManyField(related_name='products_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
